export const SEARCH_ARTISTS_DONE = 'SEARCH_ARTISTS_DONE';
export const SEARCH_ALBUMS_DONE = 'SEARCH_ALBUMS_DONE';
export const SELECT_ARTIST = 'SELECT_ARTIST';
export const SELECT_ALBUM = 'SELECT_ALBUM';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';